name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  jobs:
    test:
      runs-on: ubuntu-latest
      services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test_app
      steps:
        - uses: actions/checkout@v2
        - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '2.7.2'
        - name: Install dependencies
          run: |
            gem install bundler
            bundle install --jobs 4 --retry 3
        - name: Create and migrate database
          run: |
            bundle exec rake db:create
            bundle exec rake db:migrate
        - name: Run tests
          run: bundle exec rspec
